substitutions:
  name: Lyras Room
  friendly_name: Lyra Sense360

esphome:
  name: sense360-lyra
  min_version: 2024.11.0
  name_add_mac_suffix: false
  on_boot:
    - scd4x.perform_forced_calibration:
        id: my_scd4x_component
        value: 419

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# ---------------- UART for LD2412 (115200 8N1) ----------------
uart:
  - id: uart_bus_sensor
    rx_pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
    tx_pin: GPIO13
    baud_rate: 115200
    parity: NONE
    stop_bits: 1
    data_bits: 8

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  logs:
    sensor.template: DEBUG

api:
ota:
  platform: esphome

improv_serial:

time:
  - platform: homeassistant
    id: homeassistant_time

web_server:

i2c:
  sda: GPIO48
  scl: GPIO45
  id: bus_a
  scan: true

# ---------------- LD2412: Component/Hub ----------------
ld2412:
  uart_id: uart_bus_sensor
  id: my_ld2412

# ---------------- Binary Sensors ----------------
binary_sensor:
  # LD2412 logical flags
  - platform: ld2412
    ld2412_id: my_ld2412
    has_target:
      name: "${name} Presence"
    has_moving_target:
      name: "${name} Moving Target"
    has_still_target:
      name: "${name} Still Target"
    dynamic_background_correction_status:
      name: "${name} Dynamic Background Correction"

# ---------------- Sensors ----------------
sensor:
  # LTR-303 ALS
  - platform: ltr_als_ps
    i2c_id: bus_a
    address: 0x29
    type: ALS
    gain: 8X
    ambient_light:
      name: "${name} Ambient Light"
    full_spectrum_counts:
      name: "${name} Full Spectrum Counts"
    infrared_counts:
      name: "${name} Infrared Counts"
    update_interval: 30s

  # SCD4x (CO₂)
  - platform: scd4x
    id: my_scd4x_component
    measurement_mode: periodic
    automatic_self_calibration: true
    co2:
      name: "${name} CO₂"
      id: scd40_co2

  # SEN5x (PM/VOC/NOx/Temp/Humidity)
  - platform: sen5x
    id: AQS
    pm_1_0:
      name: "${name} PM <1µm Weight concentration"
      id: pm_1_0
      accuracy_decimals: 1
    pm_2_5:
      name: "${name} PM <2.5µm Weight concentration"
      id: pm_2_5
      accuracy_decimals: 1
    pm_4_0:
      name: "${name} PM <4µm Weight concentration"
      id: pm_4_0
      accuracy_decimals: 1
    pm_10_0:
      name: "${name} PM <10µm Weight concentration"
      id: pm_10_0
      accuracy_decimals: 1
    temperature:
      name: "${name} Temperature"
      id: temp
      accuracy_decimals: 1
    humidity:
      name: "${name} Humidity"
      id: humidity
      accuracy_decimals: 0
    voc:
      name: "${name} VOC"
      id: voc
    nox:
      name: "${name} NOX"
      id: nox
    update_interval: 10s

  # LD2412 measurements
  - platform: ld2412
    ld2412_id: my_ld2412
    moving_distance:
      name: "${name} LD2412 Moving Distance"
    still_distance:
      name: "${name} LD2412 Still Distance"
    moving_energy:
      name: "${name} LD2412 Moving Energy"
    still_energy:
      name: "${name} LD2412 Still Energy"
    detection_distance:
      name: "${name} LD2412 Detection Distance"
    light:
      name: "${name} LD2412 Light"
    gate_0:
      move_energy:  { name: "${name} Gate 0 Move Energy" }
      still_energy: { name: "${name} Gate 0 Still Energy" }
    gate_1:
      move_energy:  { name: "${name} Gate 1 Move Energy" }
      still_energy: { name: "${name} Gate 1 Still Energy" }
    gate_2:
      move_energy:  { name: "${name} Gate 2 Move Energy" }
      still_energy: { name: "${name} Gate 2 Still Energy" }
    gate_3:
      move_energy:  { name: "${name} Gate 3 Move Energy" }
      still_energy: { name: "${name} Gate 3 Still Energy" }
    gate_4:
      move_energy:  { name: "${name} Gate 4 Move Energy" }
      still_energy: { name: "${name} Gate 4 Still Energy" }
    gate_5:
      move_energy:  { name: "${name} Gate 5 Move Energy" }
      still_energy: { name: "${name} Gate 5 Still Energy" }
    gate_6:
      move_energy:  { name: "${name} Gate 6 Move Energy" }
      still_energy: { name: "${name} Gate 6 Still Energy" }
    gate_7:
      move_energy:  { name: "${name} Gate 7 Move Energy" }
      still_energy: { name: "${name} Gate 7 Still Energy" }
    gate_8:
      move_energy:  { name: "${name} Gate 8 Move Energy" }
      still_energy: { name: "${name} Gate 8 Still Energy" }
    gate_9:
      move_energy:  { name: "${name} Gate 9 Move Energy" }
      still_energy: { name: "${name} Gate 9 Still Energy" }
    gate_10:
      move_energy:  { name: "${name} Gate 10 Move Energy" }
      still_energy: { name: "${name} Gate 10 Still Energy" }
    gate_11:
      move_energy:  { name: "${name} Gate 11 Move Energy" }
      still_energy: { name: "${name} Gate 11 Still Energy" }
    gate_12:
      move_energy:  { name: "${name} Gate 12 Move Energy" }
      still_energy: { name: "${name} Gate 12 Still Energy" }
    gate_13:
      move_energy:  { name: "${name} Gate 13 Move Energy" }
      still_energy: { name: "${name} Gate 13 Still Energy" }

# ---------------- Switches ----------------
switch:
  - platform: template
    name: "Start Fan Auto Clean"
    turn_on_action:
      - sen5x.start_fan_autoclean: AQS

  - platform: ld2412
    ld2412_id: my_ld2412
    engineering_mode:
      name: "${name} LD2412 Engineering Mode"
    bluetooth:
      name: "${name} LD2412 Bluetooth"

# ---------------- Numbers (tuning) ----------------
number:
  - platform: ld2412
    ld2412_id: my_ld2412
    timeout:
      name: "${name} Presence Timeout"
    min_distance_gate:
      name: "${name} Min Distance Gate"
    max_distance_gate:
      name: "${name} Max Distance Gate"
    light_threshold:
      name: "${name} Light Threshold"
    gate_0:
      move_threshold:  { name: "${name} Gate 0 Move Threshold" }
      still_threshold: { name: "${name} Gate 0 Still Threshold" }
    gate_1:
      move_threshold:  { name: "${name} Gate 1 Move Threshold" }
      still_threshold: { name: "${name} Gate 1 Still Threshold" }
    gate_2:
      move_threshold:  { name: "${name} Gate 2 Move Threshold" }
      still_threshold: { name: "${name} Gate 2 Still Threshold" }
    gate_3:
      move_threshold:  { name: "${name} Gate 3 Move Threshold" }
      still_threshold: { name: "${name} Gate 3 Still Threshold" }
    gate_4:
      move_threshold:  { name: "${name} Gate 4 Move Threshold" }
      still_threshold: { name: "${name} Gate 4 Still Threshold" }
    gate_5:
      move_threshold:  { name: "${name} Gate 5 Move Threshold" }
      still_threshold: { name: "${name} Gate 5 Still Threshold" }
    gate_6:
      move_threshold:  { name: "${name} Gate 6 Move Threshold" }
      still_threshold: { name: "${name} Gate 6 Still Threshold" }
    gate_7:
      move_threshold:  { name: "${name} Gate 7 Move Threshold" }
      still_threshold: { name: "${name} Gate 7 Still Threshold" }
    gate_8:
      move_threshold:  { name: "${name} Gate 8 Move Threshold" }
      still_threshold: { name: "${name} Gate 8 Still Threshold" }
    gate_9:
      move_threshold:  { name: "${name} Gate 9 Move Threshold" }
      still_threshold: { name: "${name} Gate 9 Still Threshold" }
    gate_10:
      move_threshold:  { name: "${name} Gate 10 Move Threshold" }
      still_threshold: { name: "${name} Gate 10 Still Threshold" }
    gate_11:
      move_threshold:  { name: "${name} Gate 11 Move Threshold" }
      still_threshold: { name: "${name} Gate 11 Still Threshold" }
    gate_12:
      move_threshold:  { name: "${name} Gate 12 Move Threshold" }
      still_threshold: { name: "${name} Gate 12 Still Threshold" }
    gate_13:
      move_threshold:  { name: "${name} Gate 13 Move Threshold" }
      still_threshold: { name: "${name} Gate 13 Still Threshold" }

# ---------------- Buttons ----------------
button:
  - platform: ld2412
    ld2412_id: my_ld2412
    factory_reset:
      name: "${name} LD2412 Factory Reset"
    restart:
      name: "${name} LD2412 Restart"
    query_params:
      name: "${name} LD2412 Query Params"
    start_dynamic_background_correction:
      name: "${name} Start Dynamic Background Correction"

# ---------------- Text Sensors ----------------
text_sensor:
  - platform: template
    name: "${name} PM 1.0 Status"
    lambda: |-
      if (id(pm_1_0).state < 10) return {"★★★★ Good"};
      else if (id(pm_1_0).state < 20) return {"★★★☆ Moderate"};
      else if (id(pm_1_0).state < 50) return {"★★☆☆ Unhealthy"};
      else return {"★☆☆☆ Hazardous"};

  - platform: template
    name: "${name} PM 2.5 Status"
    lambda: |-
      if (id(pm_2_5).state < 12) return {"★★★★ Good"};
      else if (id(pm_2_5).state < 35) return {"★★★☆ Moderate"};
      else if (id(pm_2_5).state < 150) return {"★★☆☆ Unhealthy"};
      else return {"★☆☆☆ Hazardous"};

  - platform: template
    name: "${name} PM 4.0 Status"
    lambda: |-
      if (id(pm_4_0).state < 15) return {"★★★★ Good"};
      else if (id(pm_4_0).state < 40) return {"★★★☆ Moderate"};
      else if (id(pm_4_0).state < 200) return {"★★☆☆ Unhealthy"};
      else return {"★☆☆☆ Hazardous"};

  - platform: template
    name: "${name} PM 10.0 Status"
    lambda: |-
      if (id(pm_10_0).state < 50) return {"★★★★ Good"};
      else if (id(pm_10_0).state < 100) return {"★★★☆ Moderate"};
      else if (id(pm_10_0).state < 250) return {"★★☆☆ Unhealthy"};
      else return {"★☆☆☆ Hazardous"};

  - platform: template
    name: "${name} NOx Status"
    lambda: |-
      if (id(nox).state < 50) return {"★★★★ Good"};
      else if (id(nox).state < 100) return {"★★★☆ Moderate"};
      else if (id(nox).state < 300) return {"★★☆☆ Unhealthy"};
      else return {"★☆☆☆ Hazardous"};

  - platform: template
    name: "${name} VOC Status"
    lambda: |-
      if (id(voc).state < 50) return {"★★★★ Good"};
      else if (id(voc).state < 100) return {"★★★☆ Moderate"};
      else if (id(voc).state < 300) return {"★★☆☆ Unhealthy"};
      else return {"★☆☆☆ Hazardous"};

  # LD2412 metadata (single block; unique names)
  - platform: ld2412
    ld2412_id: my_ld2412
    version:
      name: "${name} LD2412 Firmware Version"
      entity_category: diagnostic
    mac_address:
      name: "${name} LD2412 MAC Address"
      entity_category: diagnostic

# ---------------- Selects ----------------
select:
  - platform: ld2412
    ld2412_id: my_ld2412
    out_pin_level:
      name: "${name} LD2412 OUT Pin Level"
    distance_resolution:
      name: "${name} LD2412 Distance Resolution"
    light_function:
      name: "${name} LD2412 Light Function"
    baud_rate:
      name: "${name} LD2412 Baud Rate"
