esphome:
  name: sense360-example
  friendly_name: Sense360 Example Device
  platform: ESP32
  board: esp32-s3-devkitc-1

# Wi-Fi credentials are provided through secrets (e.g., secrets.yaml or
# environment-provided substitutions) to avoid committing sensitive data.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Sense360 Example Fallback"

logger:

api:

ota:
  # The OTA password is injected via secrets or build-time substitutions.
  # For example, define `ota_password` in secrets.yaml or pass it through
  # ESPHome's `--define ota_password=` command-line option.
  password: !secret ota_password

captive_portal:

improv_serial:

sensor:
  - platform: uptime
    name: "Sense360 Example Uptime"
