name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Aggregate build manifest
        run: python scripts/aggregate-manifest.py

      - name: Upload combined manifest
        uses: actions/upload-artifact@v4
        with:
          name: combined-manifest
          path: dist/manifest.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.bin
            dist/manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
