name: Release

on:
  workflow_run:
    workflows:
      - Build ESPHome Release
    types:
      - completed

permissions:
  contents: write

jobs:
  create-release:
    if: >-
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'push' &&
        startsWith(github.event.workflow_run.head_branch, 'v')
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: dist
          merge-multiple: true

      - name: Aggregate build manifest
        run: python scripts/aggregate-manifest.py

      - name: Upload combined manifest
        uses: actions/upload-artifact@v4
        with:
          name: combined-manifest
          path: dist/manifest.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          target_commitish: ${{ github.event.workflow_run.head_sha }}
          files: |
            dist/**/*.bin
            dist/manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
